apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        #image: ghcr.io/dosedetelemetria/projeto-otel-na-pratica/users:latest
        image: projeto-otel-na-pratica/users:local
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plans
  template:
    metadata:
      labels:
        app: plans
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/plans"
    spec:
      containers:
      - name: plans
        image: ghcr.io/dosedetelemetria/projeto-otel-na-pratica/plans:latest
        ports:
        - containerPort: 8082
        env:
          - name: OTEL_SERVICE_NAME
            value: "plans"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.version=0.0.1,service.owner=grupo-5"

---
apiVersion: v1
kind: Service
metadata:
  name: plans
spec:
  selector:
    app: plans
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/subscriptions"
    spec:
      containers:
      - name: subscriptions
        image: ghcr.io/dosedetelemetria/projeto-otel-na-pratica/subscriptions:latest
        ports:
        - containerPort: 8083
        env:
          - name: OTEL_SERVICE_NAME
            value: "subscriptions"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.version=0.0.1,service.owner=grupo-5"
        securityContext:
          runAsUser: 0
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions
spec:
  selector:
    app: subscriptions
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/payments"
    spec:
      containers:
      - name: payments
        image: ghcr.io/dosedetelemetria/projeto-otel-na-pratica/payments:latest
        ports:
        - containerPort: 8084
        env:
          - name: OTEL_SERVICE_NAME
            value: "payments"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.version=0.0.1,service.owner=grupo-5"

---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  type: ClusterIP