file_format: "0.3"
disabled: false
resource:
  schema_url: https://opentelemetry.io/schemas/1.26.0
  attributes:
    - name: service.name
      value: "users"
    - name: service.version
      value: "0.0.1"
    - name: other
      value: "one-more"
propagator:
  composite: [ tracecontext, baggage ]
#tracer_provider:
#  processors:
#    - simple:
#        exporter:
#          console: {}
#    - batch:
#        exporter:
#          otlp:
#            protocol: http/protobuf
#            endpoint: http://localhost:4318
#
#meter_provider:
#  readers:
#    - periodic:
#        exporter:
#          console: {}
#    - periodic:
#        interval: 1000
#        exporter:
#          otlp:
#            protocol: http/protobuf
#            endpoint: http://localhost:4318
#
#logger_provider:
#  processors:
#    - simple:
#        exporter:
#          console: {}
#    - batch:
#        exporter:
#          otlp:
#            protocol: http/protobuf
#            endpoint: http://localhost:4318